### PR TITLE
Checkbox switch label styling

### PR DESCRIPTION
**Pull request by discodavey**

### CODE REVIEW

**Comment by discodavey** [comment]
Can you do a push if review is good enough

**Comment by de-code** [comment]
Including screenshots of the change:

image

and:

image

**Comment by discodavey** [comment]
That is correct as Chris wants the label to be highlighted on which one is selected.

**Review by de-code — APPROVED** [review]

**Comment by de-code** [comment]
> That is correct as Chris wants the label to be highlighted on which one is selected.

I was just going to record it as I am not as good at visualising CSS in my head.

As if by magic, your change seems to be deployed already.

**Pull request merged**
