### PR TITLE
make conversion result available to texture

### PR DESCRIPTION
**Pull request by de-code**

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Can you add a `project_tests.sh` file running `setup.sh` and your smoke tests so that we can use it in a `Jenkinsfile` build?

**Comment by de-code** [comment]
Added _project_tests.sh_

**Comment by giorgiosironi** [comment]
Currently building at https://alfred.elifesciences.org/job/pull-requests-projects/job/sciencebeam-texture/view/change-requests/job/PR-3/

**Comment by giorgiosironi** [comment]
I assume a `docker-compose up` is needed before running tests.

**Comment by de-code** [comment]
Yes, `docker-compose up` is needed.

**Comment by giorgiosironi** [comment]
:man_dancing:

**Review by giorgiosironi — APPROVED** [review]

**Pull request merged**
