### PR TITLE
updated logo

### PR DESCRIPTION
**Pull request by de-code**
Hi @davidcmoulton I tried to update the logo.

I took the main svg and png from the [resources page](https://elifesciences.org/resources).

I lifted the logo only svg (and some CSS) from the elife website ([link](https://elifesciences.org/assets/patterns/img/patterns/organisms/elife-logo-symbol.d2b2f600.svg)).

I deleted other logo files that didn't seem to be used. But I may not have looked long enough. Hopefully I didn't mess it up.

### logo with text

image

### logo only

image

### CODE REVIEW

**Review by davidcmoulton — COMMENTED** [review]
Not spun it up, but the changes look good to me.

@discodavey you want to approve this one?

**Comment by discodavey** [comment]
@davidcmoulton Will have as look shortly

**Review by discodavey — CHANGES_REQUESTED** [review]
When the eLife Logo is on it's own on small devices it needs more margin/padding around it like it does on the main eLife Journal site.

What currently looks like:
Screenshot 2020-05-19 at 11 45 14

This is what it should be like:

Screenshot 2020-05-19 at 11 43 53

**Comment by de-code** [comment]
Thanks Dave for having a look.

Do you have a suggesting where in the CSS it should be changed?

**Comment by discodavey** [comment]
I have not forgotten you. Will look at this after lunch.

**Comment by discodavey** [comment]
The reason that the padding is not there is that you do not have the secondary navigation in which is what makes the height up. If you will need to make sure the height is 40px but to make it even then you may need to reduce it to 38px.

See how you go.

**Comment by de-code** [comment]
Hi @discodavey thank you for looking into this. I added `min-height` `38px` to `site-header__title`.

This seem to look fine now.

### At narrow width

image

### Full width as before

image

**Comment by de-code** [comment]
Hi @discodavey are you okay with the changes?

**Comment by discodavey** [comment]
All looks good to me.

**Pull request merged**
