### PR TITLE
Text changes misc review

### PR DESCRIPTION
**Pull request by discodavey**

### CODE REVIEW

**Comment by discodavey** [comment]
@de-code These are changes that @chugginselifesciences has requested. Please can you review the code and approve.

**Comment by de-code** [comment]
My humble suggestion now that the grey text is smaller is to break the line before `Choose the "Other" model for publisher typeset papers.`.

**Review by de-code — APPROVED** [review]

**Comment by de-code** [comment]
Screenshot of the change, before:

image

after:

image

**Comment by discodavey** [comment]
@chugginselifesciences What are your thoughts on @de-code comments?

**Comment by chris-huggins** [comment]
> @chugginselifesciences What are your thoughts on @de-code comments?

Sorry for missing this. Sounds good to me.

**Comment by discodavey** [comment]
@de-code Ok to merge as added a line break as per your suggestion?

**Pull request merged**
