### PR TITLE
fixed biorxiv sciencebeam api proxy update readme

### PR DESCRIPTION
**Pull request by de-code**
Hopefully the README update will make things more clear.
I also fixed the biorxiv ScienceBeam API proxy. i.e. it should then work for both model types.

### CODE REVIEW

**Comment by discodavey** [comment]
@de-code I have just run this in from within demo and got a 500 error.

**Comment by de-code** [comment]
> @de-code I have just run this in from within demo and got a 500 error.

What command did you run?

**Comment by discodavey** [comment]
It's ok.. runs on port 8000 (Also runs on 3000 as well). Can we document that in the README file please?

Means that everything is clear so we can just follow the instructions step by step including port numbers.

**Review by discodavey — APPROVED** [review]
Left comments about documenting on README file with Port numbers etc

**Comment by de-code** [comment]
> It's ok.. runs on port 8000 (Also runs on 3000 as well). Can we document that in the README file please?
> 
> Means that everything is clear so we can just follow the instructions step by step including port numbers.

Port 8000 is for the site run via Docker at the root (and documented there). I think I documented the ports correctly now. But what may have happened is that GROBID is taking a long time to load the models (which are lazily loaded) and either the proxy or nginx is giving up. It then seem to work the second time (after GROBID has already loaded the model). I couldn't reliably reproduce it though.

**Comment by de-code** [comment]
I couldn't work out so far what timeout configuration might be responsible. Any configuration I tried resulted in a 504 rather than 500 error. I just added a note to the README.
(Also every time I tried it since it was working first time)

**Pull request merged**
