### PR TITLE
Adding width to checkbox switch labels

### PR DESCRIPTION
**Pull request by discodavey**

### CODE REVIEW

**Comment by discodavey** [comment]
@de-code One small change.

**Comment by de-code** [comment]
Just including screenshots, before:

image

after:

image

**Comment by de-code** [comment]
I think it looked better before as the gap was the same. This is what Chris requested?

**Comment by discodavey** [comment]
It stops the checkbox and other label moving right to left when you select biorxiv.

**Comment by de-code** [comment]
> It stops the checkbox and other label moving right to left when you select biorxiv.

Okay, I will leave it to you and Chris to decide.
Maybe it would make sense to add a similar gap on the 'other' side?

**Review by de-code — APPROVED** [review]

**Comment by de-code** [comment]
(merge if you are happy with it, I will create a GitHub release afterwards)

**Pull request merged**
